name: nlp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.3.0
  - astroid=2.3.3
  - attrs=19.3.0
  - automat=0.8.0
  - bcrypt=3.1.7
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - constantly=15.1.0
  - cryptography=2.8
  - cssselect=1.1.0
  - hyperlink=19.0.0
  - icu=58.2
  - idna=2.9
  - incremental=17.5.0
  - isort=4.3.21
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.5.0
  - mccabe=0.6.1
  - more-itertools=8.2.0
  - ncurses=6.2
  - nltk=3.4.5
  - openssl=1.1.1e
  - packaging=20.3
  - parsel=1.5.2
  - pip=20.0.2
  - pluggy=0.13.1
  - py=1.8.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydispatcher=2.0.5
  - pyhamcrest=1.9.0
  - pylint=2.4.4
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pytest=5.4.1
  - pytest-runner=5.2
  - python=3.8.1
  - queuelib=1.5.0
  - readline=7.0
  - scrapy=1.6.0
  - service_identity=18.1.0
  - setuptools=46.0.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - twisted=19.10.0
  - w3lib=1.21.0
  - wcwidth=0.1.8
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.4
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.7.1
  - pip:
    - alabaster==0.7.12
    - allennlp==0.9.0
    - arrow==0.15.5
    - babel==2.8.0
    - beautifulsoup4==4.8.2
    - bibtexparser==1.1.0
    - blis==0.2.4
    - boto3==1.12.27
    - botocore==1.15.27
    - catalogue==1.0.0
    - chardet==3.0.4
    - click==7.1.1
    - conllu==1.3.1
    - cycler==0.10.0
    - cymem==2.0.3
    - docutils==0.15.2
    - editdistance==0.5.3
    - en-core-web-sm==2.1.0
    - flaky==3.6.1
    - flask==1.1.1
    - flask-cors==3.0.8
    - ftfy==5.7
    - future==0.18.2
    - gevent==1.4.0
    - greenlet==0.4.15
    - h5py==2.10.0
    - imagesize==1.2.0
    - itsdangerous==1.1.0
    - jinja2==2.11.1
    - jmespath==0.9.5
    - joblib==0.14.1
    - jsonnet==0.15.0
    - jsonpickle==1.3
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - murmurhash==1.0.2
    - numpy==1.18.2
    - numpydoc==0.9.2
    - overrides==2.8.0
    - parsimonious==0.8.1
    - pdfminer==20191125
    - plac==0.9.6
    - preshed==2.0.1
    - protobuf==3.11.3
    - pycryptodome==3.9.7
    - pygments==2.6.1
    - python-dateutil==2.8.1
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pytz==2019.3
    - regex==2020.2.20
    - requests==2.23.0
    - responses==0.10.12
    - s3transfer==0.3.3
    - scholarly==0.2.5
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - sentencepiece==0.1.85
    - snowballstemmer==2.0.0
    - soupsieve==2.0
    - spacy==2.1.9
    - sphinx==2.4.4
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sqlparse==0.3.1
    - srsly==1.0.2
    - tensorboardx==2.0
    - thinc==7.0.8
    - torch==1.4.0
    - tqdm==4.43.0
    - unidecode==1.1.1
    - urllib3==1.25.8
    - wasabi==0.6.0
    - werkzeug==1.0.0
    - word2number==1.1

